Ditt NAV varsel for omsorgspenger-midlertidig-alene
navikt/sif-innsyn-api pull request #16
Opened 2020-11-25 13:27 UTC by SanderOpperud

Konsumerer på cleanup topicen til midlertidig-alene og sender ut varsel. Lagrer ikke søknaden

2020-11-25 13:40 UTC, ramrock93 requested changes

2020-11-25 13:40 UTC, ramrock93 commented on src/test/kotlin/no/nav/sifinnsynapi/common/TransactionRollbackTest.kt
> +    @Ignore
Ikke ignorerer testen. Se om det hjelper å sette await.atMost til 120. Bruker sikkert litt ekstra når den må restarte transaksjonen.

2020-11-25 15:48 UTC, SanderOpperud commented on src/test/kotlin/no/nav/sifinnsynapi/common/TransactionRollbackTest.kt
> +    @Ignore
Fikset i ny commit :P

2020-11-26 06:37 UTC, ramrock93 approved these changes
LGTM

2020-11-26 08:32 UTC, merged